# Data paths
data:
  train_path: "data/data.csv"
  test_size: 0.2
  random_state: 42

# Feature engineering
features:
  categorical_columns:
    - town
    - flat_type
    - storey_range
    - flat_model
    - block
    - street_name
  numerical_columns:
    - floor_area_sqm
    - lease_commence_date
    - remaining_lease
  target_column: "resale_price"

# Model parameters
models:
  linear_regression:
    fit_intercept: true
  
  xgboost:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 7
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  lightgbm:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 7
    num_leaves: 31
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  catboost:
    iterations: 1000
    learning_rate: 0.01
    depth: 7
    l2_leaf_reg: 3
    random_state: 42

# Training settings
training:
  cv_folds: 5
  scoring: "neg_mean_squared_error"
  n_jobs: -1 